### PR TITLE
Enable contextMenu event

### PR DESCRIPTION
**Pull request by octavm**

### CODE REVIEW

**Comment by mstahv** [comment]
Excellent stuff! This has been a frequently asked feature. The code looks awesome too, with an IT test/code example it would have been perfect. I'll get on testing it right away...

**Comment by mstahv** [comment]
Seems to work perfectly: https://github.com/mstahv/v-leaflet/commit/762bbfa31f36abf0d4f84e2fd666abe7946d366f

On a tile layers, like OSM layer, I couldn't get it work, but the same goes for normal clicks. I think new Leaflet 1.0 should support this, but something should be changed/added probably in v-leaflet connectors.

**Comment by mstahv** [comment]
@octavm , let me know if you want to cut a release. I could do it only for this feature. Big thanks!

**Comment by mstahv** [comment]
@octavm , would you like to work adding some API to get the pixel position of the click as well to the events? Then it would be easy to combine this with e.g. https://vaadin.com/directory#!addon/contextmenu and that way make the feature even more handy.

**Comment by mstahv** [comment]
An asynchronous LMap.getPixelCoordinates(Point, Callback) would be handy as well in some cases.

**Comment by mstahv** [comment]
I'll have a look at this shortly in https://github.com/mstahv/v-leaflet/issues/99

**Comment by octavm** [comment]
Thanks! It was my pleasure to help - I hope it will come in handy to many using the v-leaflet plugin.

**Comment by octavm** [comment]
Yes, please ! A release with these changes will be great. Thanks!

**Pull request merged**
