### PR TITLE
Added events overlayadd, overlayremove

### PR DESCRIPTION
**Pull request by octavm**
Bring this change into 1.x versions of v-leaflet, compatible with vaadin-7

### CODE REVIEW

**Comment by mstahv** [comment]
Ping me if I don't remember to cut a release soon!

**Comment by octavm** [comment]
Matti, could we get a release of the latest 1.x v-leaflet in Vaadin Directory ? To get this pull request and the g-leaflet fix for the missing control icon (g-leaflet pull-#55)

**Comment by mstahv** [comment]
Sure, I'm returning from a skiing holiday. I'll look into this tomorrow.

**Comment by mstahv** [comment]
There you go!

**Comment by octavm** [comment]
Thanks a lot!

**Pull request merged**
