### PR TITLE
Added 'overlayadd' and 'overlayremove' events

### PR DESCRIPTION
**Pull request by octavm**
Test scenario added in BasicTest class.

### CODE REVIEW

**Comment by basisbit** [comment]
your pom.xml change breaks travis-ci build because that 1.0.7-SNAPSHOT g-leaflet version is missing.
Maybe the travis-build should be changed to get and compile the g-leaflet dependency instead of trying to pull some pre-built version?

**Comment by basisbit** [comment]
also, this depends on https://github.com/mstahv/g-leaflet/pull/53

**Comment by mstahv** [comment]
Yes, it happens and I don't know how we could fix that otherwise but putting g-leaflet into the same source code repository.

The change looks good to me. I merged the g-leaflet change right away.

What would be the real use case for this feature? Are there some overlayadd events that happen via client side only? If not, maybe the same feature for v-leaflet would make more sense to implement on the server side code only? In fact, I think it could be really good Vaadin core feature for AbstractComponentContainer.

**Comment by octavm** [comment]
The use is demonstrated in the BasicTest class.
Using these two events the server is informed which overlays are currently active (added to the map). Without these two events the server side isn't aware of what's happening on the client side(which overlay checkbox has been clicked).
I'm not sure I follow your last question, you want to implement this in vaadin class AbstractComponentContainer? This change is for leaflet overlays, implementing Leaflet Map events described here: [overlayadd event](http://leafletjs.com/reference-1.2.0.html#map-overlayadd), [overlayremove event](http://leafletjs.com/reference-1.2.0.html#map-overlayremove)

**Comment by mstahv** [comment]
Oh, yes, now that I read the documentation and figured out that the event is via layers controls, this makes perfectly sense. I think actually that somebody has asked to implement this previously as well.

**Comment by mstahv** [comment]
BTW. I added my own public maven repository as snapshot repository to the project. Now if there is aan unreleased change in g-leaflet that v-leaflet project depends on, I can build a SNAPSHOT of g-leaflet and then v-leaflet travis build will find it. But it is still not automatic though.

**Pull request merged**
