### PR TITLE
Migrated JTS to Eclipse foundation version

### PR DESCRIPTION
**Pull request by willtemperley**
GeoJSON tests don't work as the Geotools people haven't migrated JTS yet

### CODE REVIEW

**Comment by mstahv** [comment]
Cool, I hadn't even followed that JTS is being moved to Eclipse. GeoJSON apparently don't work as you stated, but do you know how this change affects other tools like spatial extensions in Hibernate etc? Are you in rush to move to the new version? I'd at least wait for Geotools as I have been using that in certain apps. One option would be to create two branches and cut a version with the new JTS library.

**Comment by willtemperley** [comment]
That's a good question and it seems that hibernate spatial is still on the pre-eclipse foundation version.
So it seems this PR would cause more problems than it will solve.

Just FYI there's been a big effort to move many geospatial libraries to [LocationTech](https://www.locationtech.org/) partly to remove the many of the licensing issues and partly to breathe new life into stagnating projects.

Perhaps it's something to revisit when everything gets reworked for Vaadin 10 :) which I'm trying to get my head around now.

**Comment by mstahv** [comment]
Let's keep this open and submit if we get enough evidence that most people are using the locationtech libraries. I have also spent couple of days with Flow components/development and based that I think this project will live long still ;-)

Have you tried creating V10/WebComponent based Leaflet integration already? IIRC somebody had made a WebComponent wrapper for LeafletJS, so that should in theory be a great start for V10 integration.

**Comment by willtemperley** [comment]
Ok sure, let's keep it open and see what happens with JTS. 

:-) So you're saying a V10 RC is somewhat far in the future?

I'm experimenting right now with creating a LeafletJS webcomponent.  There's a Polymer 1.0 version  (https://github.com/leaflet-extras/leaflet-map) which is a good starting point, perhaps that's the one you mean.  It's abandonware so I'm starting to migrate that to Polymer 2.0. I'm just learning all this stuff so it's not going to happen quickly.  First half an hour's work here, but it might as well be called 'my-first-web-component':
https://github.com/willtemperley/leaflet-map

**Comment by mstahv** [comment]
There is a meeting tomorrow to decided if we should go to beta stage soon or not, I wouldn't be surprised of a yet another delay. It is a huge renewal and lot of things to get polished.

Good to know that you are working on Polymer 2 version, will follow how your project continues.

**Comment by willtemperley** [comment]
Interesting. It is a huge change but it's getting difficult to avoid JavaScript these days I suppose. At least there seems to be some sanity in the newer standards.

**Comment by mstahv** [comment]
Hibernate spatial going to the locationtech namespace soon:

https://github.com/hibernate/hibernate-orm/commit/b3e56a5db71110d07a095762a788c53ef258bd01

**Comment by mstahv** [comment]
I think the time for this is now. Hibernate 5.4 series now also uses the "new jts".

I'll cut one more release with old jts, then move to next major version and will take this in.

**Pull request merged**
